
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


/**
 * @author RAMIRO
 */
public class MyKeepers extends javax.swing.JFrame {
    
    String tipoRegistro;
    
    PreparedStatement pstm;
    
    ResultSet rs;
    
    List<KeepBean> Keeps;
    
    DefaultTableModel tmKeepers = new DefaultTableModel(null, new String[]{"Site/Serviço"}) {

        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };

    ListSelectionModel lsmServicos;
    /**
     * Creates new form MyKeepers
     */
    public MyKeepers() {
        initComponents();
        AtualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbSite = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfSite = new javax.swing.JTextField();
        tfTipo = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfUser = new javax.swing.JTextField();
        tfSenha = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador Pessoal de Senhas");
        setLocation(new java.awt.Point(400, 250));
        setPreferredSize(new java.awt.Dimension(630, 300));
        setResizable(false);

        tbSite.setModel(tmKeepers);
        tbSite.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  
        lsmServicos = tbSite.getSelectionModel();  
        lsmServicos.addListSelectionListener(new ListSelectionListener() {          
            public void valueChanged(ListSelectionEvent e){          
                if(!e.getValueIsAdjusting()){          
                    mostraDadosTF(tbSite);  
                }  
            }  
        });
        jScrollPane1.setViewportView(tbSite);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Site / Serviço:");

        jLabel2.setText("E-Mail:");

        jLabel3.setText("Usuário:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Tipo de Site / Serviço:");

        tfSite.setEditable(false);

        tfTipo.setEditable(false);

        tfEmail.setEditable(false);

        tfUser.setEditable(false);

        tfSenha.setEditable(false);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/gravar_registro.gif"))); // NOI18N
        btSalvar.setToolTipText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar_registro.gif"))); // NOI18N
        btEditar.setToolTipText("Alterar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.gif"))); // NOI18N
        btExcluir.setToolTipText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cancelar.gif"))); // NOI18N
        btCancelar.setToolTipText("Limpar / Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.gif"))); // NOI18N
        btSair.setToolTipText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo_registro.gif"))); // NOI18N
        btNovo.setToolTipText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTipo)
                            .addComponent(tfEmail)
                            .addComponent(tfUser)
                            .addComponent(tfSenha)
                            .addComponent(tfSite)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addComponent(btNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btEditar, btExcluir, btNovo, btSair, btSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btEditar)
                    .addComponent(btExcluir)
                    .addComponent(btCancelar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btNovo)
                        .addComponent(btSalvar))
                    .addComponent(btSair))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCancelar, btEditar, btExcluir, btNovo, btSair, btSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        tipoRegistro = "novo";
        LimparCampos();
        HabilitarCampos();
        tfSite.requestFocus();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        LimparCampos();
        DesabilitarCampos();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if(tipoRegistro.equals("novo")){
            Salvar();
        }else{
            Atualizar();
        }
        LimparCampos();
        DesabilitarCampos();
        AtualizarTabela();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        tipoRegistro = "editar";
        HabilitarCampos();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        Deletar();
        AtualizarTabela();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void LimparCampos(){
        tfSite.setText("");
        tfTipo.setText("");
        tfEmail.setText("");
        tfUser.setText("");
        tfSenha.setText("");
    }
    
    private void HabilitarCampos(){
        tfSite.setEditable(true);
        tfTipo.setEditable(true);
        tfEmail.setEditable(true);
        tfUser.setEditable(true);
        tfSenha.setEditable(true);
    }
    
    private void DesabilitarCampos(){
        tfSite.setEditable(false);
        tfTipo.setEditable(false);
        tfEmail.setEditable(false);
        tfUser.setEditable(false);
        tfSenha.setEditable(false);
    }
    
    private void Salvar(){
        KeepBean kb = new KeepBean();
        KeepControl kc = new KeepControl();
        kb.setServico(tfSite.getText());
        kb.setTiposervico(tfTipo.getText());
        kb.setEmail(tfEmail.getText());
        kb.setUsuario(tfUser.getText());
        kb.setSenha(tfSenha.getText());
        kc.Salvar(kb);
    }
    
    private void Atualizar(){
        KeepBean kb = new KeepBean();
        KeepControl kc = new KeepControl();
        kb.setServico(tfSite.getText());
        kb.setTiposervico(tfTipo.getText());
        kb.setEmail(tfEmail.getText());
        kb.setUsuario(tfUser.getText());
        kb.setSenha(tfSenha.getText());
        kc.Alterar(kb);
    }
    
    private void Deletar(){
        KeepBean kb = new KeepBean();
        KeepControl kc = new KeepControl();
        kb.setServico(tfSite.getText());
        kc.Excluir(kb);
        
    }
    
    private void AtualizarTabela(){
        Keeps = new ArrayList();
        String sql = "select * from KEEPS order by servico"; 
        ConexaoBD con = new ConexaoBD();
        try{
            pstm = con.conecta().prepareStatement(sql);
            rs = pstm.executeQuery();
            KeepBean kb;
            while (rs.next()){
                kb = new KeepBean();
                kb.setServico(rs.getString("servico"));
                kb.setTiposervico(rs.getString("tiposervico"));
                kb.setEmail(rs.getString("email"));
                kb.setUsuario(rs.getString("usuario"));
                kb.setSenha(rs.getString("senha"));
                Keeps.add(kb);
            }
            
        }catch(Exception e){
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, "Não Existe Registro!");
        }finally{
            con.desconecta();
        }
        
        tbSite.getColumnModel().getColumn(0).setPreferredWidth(10);
        
        while(tmKeepers.getRowCount() > 0){
            tmKeepers.removeRow(0);
        }        
        
        if(Keeps.size() == 0){
            //JOptionPane.showMessageDialog(this, "Nenhum Serviço Encontrado!");
        }else{
            String[] campos = new String[]{null};
            for (int i = 0; i < Keeps.size(); i++) {

            tmKeepers.addRow(campos);
            tmKeepers.setValueAt(Keeps.get(i).getServico(), i, 0);
            } 
        }
    }
    
    public void mostraDadosTF(JTable tb){
        if (tb.getSelectedRow() != -1) {
            tfSite.setText(Keeps.get(tb.getSelectedRow()).getServico());
            tfTipo.setText(Keeps.get(tb.getSelectedRow()).getTiposervico());
	    tfEmail.setText(Keeps.get(tb.getSelectedRow()).getEmail());
	    tfUser.setText(Keeps.get(tb.getSelectedRow()).getUsuario());
            tfSenha.setText(Keeps.get(tb.getSelectedRow()).getSenha());
	    
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyKeepers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyKeepers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyKeepers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyKeepers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyKeepers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSite;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfSenha;
    private javax.swing.JTextField tfSite;
    private javax.swing.JTextField tfTipo;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
